services:
  app:
    image: banksy
    container_name: banksy_app
    restart: always
    build:
      context: ./
      target: dev   # Use 'prod' if you want to build a production image
      dockerfile: Dockerfile
      no_cache: false
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/banksy_db?schema=public
      - COMPOSE_BAKE=true
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:16
    container_name: banksy_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banksy_db
    ports:
      - '5432:5432'
    volumes:
      - banksy_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  banksy_postgres_data:
  banksy_node_modules:
  banksy_next: